### ISSUE TITLE
LICENSE file

### ISSUE THREAD

**Issue by 1dot75cm** [linuxdeepin/dde-account-faces#2]
Please add LICENSE file.

**Comment by mark-stopka** [comment]
@deepinzhangshuang , yes, can you please add LICENSE file to make it easier for package maintainers?

**Comment by Justinzobel** [comment]
In the Debian folder it says that /* are available under Creative Commons Public Licenses but doesn't specify which one, ie a specific one from https://spdx.org/licenses/

**Comment by BLumia** [comment]
cc @hualet

**Comment by xmuli** [comment]
The protocol is supplemented in README.md.
